export enum ROUTES {
    HOME = '/',
    LOGIN = '/login',
    REGISTRATION = '/registration',
    OFFERSGRID = '/offersGrid',
    CREATEOFFER = '/createOffer',
    RULES = '/rules',
    ABOUT = '/about',
    PRIVACY = '/privacy',
    CONTACT = '/contact',
    USERACCOUNT = '/userAccount',
    WITHDRAWMONEY = '/withdrawMoney',
    DEPOSIT = '/deposit',
    USERHISTORY = '/userHistory',
}
