export const data = [
    {
        id: 1,
        loanAmount: 1000,
        timePeriod: 2,
        interestRate: 3,
        endDate: '2020-12-22',
    },
    {
        id: 2,
        loanAmount: 500,
        timePeriod: 10,
        interestRate: 7,
        endDate: '2020-12-22',
    },
    {
        id: 3,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
    {
        id: 4,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
    {
        id: 5,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
    {
        id: 6,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
    {
        id: 7,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
    {
        id: 8,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
    {
        id: 9,
        loanAmount: 200,
        timePeriod: 4,
        interestRate: 6,
        endDate: '2020-12-22',
    },
];

export const images = [
    'https://randomuser.me/api/portraits/men/17.jpg',
    'https://randomuser.me/api/portraits/men/29.jpg',
    'https://randomuser.me/api/portraits/women/21.jpg',
    'https://randomuser.me/api/portraits/women/2.jpg',
    'https://randomuser.me/api/portraits/men/22.jpg',
    'https://randomuser.me/api/portraits/women/66.jpg',
    'https://randomuser.me/api/portraits/men/3.jpg',
    'https://randomuser.me/api/portraits/women/45.jpg',
    'https://randomuser.me/api/portraits/women/36.jpg',
    'https://randomuser.me/api/portraits/men/1.jpg',
    'https://randomuser.me/api/portraits/men/2.jpg',
];
